# Generated by Django 4.2 on 2023-04-22 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_userstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='last_reload',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='output_size',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='timezone',
        ),
    ]
